export const CHANGE_INPUT_TEXT = 'CHANGE_INPUT_TEXT';
export const CHANGE_INPUT_DATE = 'CHANGE_INPUT_DATE';
export const CHANGE_INPUT_NUMBER = 'CHANGE_INPUT_NUMBER';
export const CHANGE_TEXTAREA = 'CHANGE_TEXTAREA';
export const CHANGE_SELECT = 'CHANGE_SELECT';
export const CHANGE_RADIO = 'CHANGE_RADIO';
export const CHANGE_CHECKBOX = 'CHANGE_CHECKBOX';
export const CONFIRM_NOT_BE_ROBOT = 'CONFIRM_NOT_BE_ROBOT';
